public enum SpellType
{
    None,
    Heal,
    Fireball,
    Teleport,
    PoisonousStrike,
    Fortify,
    SavageLeap,
    SlinkAway,
    Clairvoyance,
    Telekinesis,
    SummonSkull,
    Lift,
    Freeze,
    IceBolt,
    EnrageSpell,
    ResilienceSpell,
    WeakenSpell,
    VulnerableSpell
}