public enum StatType
{
    None,
    Strength,
    Dexterity,
    Intelligence,
    Speed,
    CritChance,
    Armor,
    Evasion,
    Accuracy,
    Range,
    MinDamage,
    MaxDamage,
    MaxHealth,
    MaxMana,
    StrengthRequirement,
    DexterityRequirement,
    IntelligenceRequirement
}
